In [5]:
import gym
env = gym.make('FrozenLake-v0')
s = env.reset()
print(s)

0


In [6]:
env.render()


SFFF
FHFH
FFFH
HFFG


In [7]:
print(env.action_space)
print(env.action_space.n)

Discrete(4)
4


In [8]:
print(env.observation_space)
print(env.observation_space.n)

Discrete(16)
16


# Q-Learning

In [9]:
print("Number of actions: ", env.action_space.n)
print("Number of states: ", env.observation_space.n)

Number of actions:  4
Number of states:  16


1. Initialize the Q-table 
2. Updateing of a Q value for a sate-action pair, that is Q(s,z) is given by:
$$Q(s,a) <= Q(s,a) +a[r + gamma*maxQ(s',a')-Q(s,a)]$$

# The Epsilon-Greedy approach

### The Epsilon-Greedy is a widely used solution to the explore-exploit dilemma.
- epsilon
- p, ranodm probability
- if p <= e: pull a random action
- else: pull current best action

In [15]:
# import dependency libraries
from __future__ import print_function
import gym
import numpy as np
import time

In [17]:
#m Load the environment
env = gym.make("FrozenLake-v0")

s = env.reset()
print("Initial state: ", s)
print()

env.render()
print()

print(env.action_space) # number of actions
print(env.observation_space) # number of states
print()

print("number of actions: ", env.action_space.n)
print("number of observations: ", env.observation_space.n)
print()



Initial state:  0


SFFF
FHFH
FFFH
HFFG

Discrete(4)
Discrete(16)

number of actions:  4
number of observations:  16



In [25]:
# Epsilon-Greedy approach for Exploration and Exploitation of the state-action sapces
def epsilon_greedy(Q,s,na):
    epsilon = 0.3
    p = np.random.uniform(low=0, high = 1)
    #print(p)
    if p> epsilon:
        return np.argmax(Q[s,:])
    else:
        return env.action_space.sample()

In [26]:
# Initialize Q-table with zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

# set hyperparameters
lr = 0.5
y = 0.9 # idscount factor lambda
eps = 100000 # total number of episodes running

for i in range(eps):
    s = env.reset()
    t = False
    while(True):
        a = epsilon_greedy(Q, s, env.action_space.n)
        s_, r, t, _ = env.step(a)
        if (r == 0):
            if t == True:
                r = -5 # to give negative rewards when  holes turn up
                Q[s_] = np.ones(env.action_space.n)*r # in terminal state Q, value == reward
            else:
                r = -1 # to give negative rewards to avoid long routes
        if (r ==1):
            r = 100
            Q[s_] = np.ones(env.action_space.n) * r 
        Q[s,a] = Q[s,a] + lr*(r+y*np.max(Q[s_,a]) - Q[s,a])
        s = s_
        if (t == True):
            break

print("Q-table")
print(Q)
print()

print("Output after leraning")
print()

# check how much an agent has learned.
s = env.reset()
env.render()
while(True):
    a = np.argmax(Q[s])
    s_,r,t,_ = env.step(a)
    print("===============")
    env.render()
    s = s_
    if (t == True):
        break
            
                

Q-table
[[ -9.83336029  -9.73139263  -9.36218174 -10.        ]
 [ -9.59962513  -9.53489536  -8.70996893 -10.        ]
 [ -9.83387104  -9.62517443   1.78863934 -10.        ]
 [ -9.68083191  -9.61080771  -9.69068235 -10.        ]
 [ -9.67808454  -3.06633029  -9.44978819  -9.81974568]
 [ -5.          -5.          -5.          -5.        ]
 [ -9.79996826  -9.49129635  14.57369204  -9.57911314]
 [ -5.          -5.          -5.          -5.        ]
 [ -9.61124388  14.20099495  -9.37929128  -9.78645531]
 [ -9.59511043  34.69802046  -6.23086972  -9.70972077]
 [ -9.67630806  18.31907288  41.63542884  -9.68502549]
 [ -5.          -5.          -5.          -5.        ]
 [ -5.          -5.          -5.          -5.        ]
 [ -9.65935759  58.77776549  -4.74925311  -9.19256109]
 [ -9.70748601  68.75205097 124.5491152   30.6394352 ]
 [100.         100.         100.         100.        ]]

Output after leraning


SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down